<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit94803d3b7e72c276defb64388e99eb24
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit94803d3b7e72c276defb64388e99eb24::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit94803d3b7e72c276defb64388e99eb24::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit94803d3b7e72c276defb64388e99eb24::$classMap;

        }, null, ClassLoader::class);
    }
}
